on:
  push:
    branches:
      - Develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t my-image .

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push registry.digitalocean.com/my-image

      - name: Install Digital Ocean CLI
        run: |
          curl -sL https://repos.insights.digitalocean.com/install.sh | sudo bash

      - name: Deploy to droplet
        run: |
          doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          droplet_name=$(doctl compute droplet list --format Name,PublicIPv4 | awk '{print $1}')
          echo "Deploying to droplet: $droplet_name"
          doctl compute ssh $droplet_name --ssh-command "cd /var/www/my-project && git pull && npm install && pm2 restart all"
